---

# Drupal
drupal_db_password: islandora
drupal_account_pass: islandora

# MySQL/Postgres
islandora_db_root_password: islandora
mysql_islandora_user_password: islandora

# Matomo
matomo_db_root_password: islandora
matomo_db_password: islandora

# Crayfish
crayfish_db_root_password: islandora
crayfish_db_password: islandora

# Tomcat
islandora_tomcat_password: islandora

# Syn
islandora_syn_token: islandora

# Cantaloupe
cantaloupe_admin_password: islandora

# Fedora
fcrepo_db_password: islandora
fcrepo_db_root_password: islandora
